START TRANSACTION;

-- Eliminar as tabelas associativas com CASCADE
DROP TABLE IF EXISTS Reporte_Comentario CASCADE;
DROP TABLE IF EXISTS Reage_Live CASCADE;
DROP TABLE IF EXISTS Live_Aderir CASCADE;
DROP TABLE IF EXISTS Playlist_Musica CASCADE;
DROP TABLE IF EXISTS Like_Musica CASCADE;
DROP TABLE IF EXISTS Like_Playlist CASCADE;
DROP TABLE IF EXISTS Doacao CASCADE;
DROP TABLE IF EXISTS Comentario CASCADE;
DROP TABLE IF EXISTS Utilizador_Notificacao CASCADE;
DROP TABLE IF EXISTS musica_categoria CASCADE;
DROP TABLE IF EXISTS segue_utilizador CASCADE;


-- Eliminar as tabelas principais com CASCADE
DROP TABLE IF EXISTS Live CASCADE;
DROP TABLE IF EXISTS Notificacao CASCADE;
DROP TABLE IF EXISTS Playlist CASCADE;
DROP TABLE IF EXISTS Musica CASCADE;
DROP TABLE IF EXISTS Categoria CASCADE;
DROP TABLE IF EXISTS Utilizador CASCADE;

COMMIT;


